### ISSUE TITLE
Create a Hoverable dropdown menu

### ISSUE THREAD

**Issue by Achlesha** [Achlesha/hactoberFest2022#23]
Create a hoverable dropdown menu that will has 3 fields:
1) Cut
2) Copy
3) Paste

**Comment by pravincoder** [comment]
i can do it for you!

**Comment by NandiniVar** [comment]
I can do it for you. Plz assign it to me.

**Comment by NandiniVar** [comment]
#24 Issue resolved. Kindly review and merge it.

**Comment by Achlesha** [comment]
This Issue has been resolved.
